### ISSUE TITLE
#fileID in a macro expansion context is malformed

### ISSUE THREAD

**Issue by grynspan** [apple/swift-syntax#1312]
### Description

Per the documentation [here](https://docs.swift.org/swift-book/ReferenceManual/Expressions.html#ID390), `#fileID` is of the form `"ModuleName/FileName"`, but the value produced from within a macro expansion context is (currently) just a filename.

**Comment by ahoppen** [comment]
@grynspan, do you know if https://github.com/apple/swift-syntax/issues/1312 is still an issue or has it been defined away by using the fileID from the expansion context? If it’s still an issue, do you have a reproducer for it?

**Comment by grynspan** [comment]
This is still an issue, because a macro expansion can't control the uses of `#fileID` and friends from developer-supplied code, and if we start talking about nesting macros, we're gonna have a bad day.

I do have a reproducer. DM me for details.

**Comment by ahoppen** [comment]
This was fixed by https://github.com/apple/swift/pull/67447.

**Comment by grynspan** [comment]
Unfortunately it wasn't, and I can still reproduce the issue in various contexts.

**Comment by grynspan** [comment]
Ignore me—was thinking of a different issue.
